@startchen

entity Pessoa {
    id: int <<key>>
    nome: String
    data_nascimento: Date
    cpf: String
    nacionalidade: String
}

entity Jogador {
    id: int <<key>>
    numero_camisa: int
    posicao: String
    altura: float
    peso: float
}

entity Partida {
    time_casa
    time_visitante
    data_e_hora
    local
}

entity Time {
    id: int <<key>>
    nome: String
    sigla: String
}

entity Rodada {
    id: int <<key>>
    numero: int
    data_inicio: Date
    data_fim: Date
}

entity Falta {
    id: int <<key>>
    partida_id: int
    jogador_id: int
    hora: DateTime
}

entity Gols {
    partida_id: int
    hora: DateTime
    pontuador_id: int
}

entity Cartao {
    id: int <<key>>
    partida_id: int
    jogador_id: int
    tipo: String
    hora: DateTime
}

entity Arbitro {
    id: int <<key>>
}

entity Tecnico {
}

entity Funcionario {
    salario: float
}

entity Torcedor {
}

Pessoa ->- o { Funcionario, Torcedor }
Funcionario ->- d { Jogador, Arbitro, Tecnico }

relationship "Trabalha em" as TrabalhaEmTime {
    matricula
    data_admissao
}

Funcionario -N- TrabalhaEmTime
TrabalhaEmTime -1- Time

relationship "Participa de" as ParticipaDePartida {
}

Time -N- ParticipaDePartida
ParticipaDePartida -N- Partida

relationship "Possui" as PossuiGols {
}

Partida -1- PossuiGols
Jogador -1- PossuiGols
PossuiGols -N- Gols

relationship "Tem" as TemPartida {
}

Rodada -1- TemPartida
TemPartida -N- Partida

relationship "Comete" as PossuiFaltas {
}

relationship "Recebe" as PossuiCartoes {
}

Partida -1- PossuiFaltas
Jogador -1- PossuiFaltas
PossuiFaltas -N- Falta

Partida -1- PossuiCartoes
Jogador -1- PossuiCartoes
PossuiCartoes -N- Cartao
@endchen